version: '3'
networks:
  mynetwork:
    driver: bridge

services:
  okrapi:
    build: 
      context: .
      dockerfile: ./OKR.API/Dockerfile
    image: karzix/okrapi:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  okrui:
    build: 
      context: .
      dockerfile: ./OKR.UI/Dockerfile
    image: karzix/okrui:latest
    ports:
      - "80:80"
    networks:
      - mynetwork

  consumerweightupdate:
    build: 
      context: .
      dockerfile: ./ConsumerWeightUpdate/Dockerfile
    image: karzix/consumerweightupdate:latest
    ports:
      - "8082:8082"
    networks:
      - mynetwork
