version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: karzix/okrapi:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

  vue:
    build:
      context: ./OKR.UI
      dockerfile: Dockerfile
    image: karzix/okrui:latest
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
