name: Deploy to Docker Hub

on:
  push:
    branches:
      - deploy  # Triển khai khi code được gộp vào nhánh deploy
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Lưu tên đăng nhập trong Secrets của GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Lưu mật khẩu Docker Hub trong Secrets của GitHub

      - name: Build and push API image
        run: |
          docker build -t karzix/api:latest ./OKR.API
          docker push karzix/api:latest

      - name: Build and push Vue image
        run: |
          docker build -t karzix/vue:latest ./OKR.UI
          docker push karzix/vue:latest
