name: Deploy to Docker Hub

on:
  push:
    branches:
      - deploy  # Triển khai khi code được gộp vào nhánh deploy
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Lưu tên đăng nhập trong Secrets của GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Lưu mật khẩu Docker Hub trong Secrets của GitHub

      - name: Build and push API image
        run: |
          docker build -t karzix/okrapi:latest ./
          docker push karzix/okrapi:latest

      - name: Build and push Vue image
        run: |
          docker build -t karzix/okrui:latest ./OKR.UI
          docker push karzix/okrui:latest

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # Lưu địa chỉ IP/hostname của server SSH trong Secrets
          username: ${{ secrets.SSH_USERNAME }}  # Lưu username của server SSH trong Secrets
          password: ${{ secrets.SSH_PASSWORD }}  # Lưu password của server SSH trong Secrets hoặc sử dụng private key
          port: 22  # Cổng SSH (mặc định là 22)
          script: |
            /bin/bash /home/deploy.sh
